apiVersion: apps/v1
kind: Deployment
metadata:
  name: typhoon-2-5-vllm
  labels:
    app: typhoon-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typhoon-vllm
  template:
    metadata:
      labels:
        app: typhoon-vllm
    spec:
      nodeSelector:
        kubernetes.io/hostname: ailprsvai02 # ระบุ node ที่มี L40S GPU
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest # หรือระบุเวอร์ชัน เช่น v0.7.0
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]  
        args:
          - "--model"
          - "typhoon-ai/typhoon2.5-qwen3-30b-a3b"
          - "--quantization"
          - "bitsandbytes"
          - "--load-format"
          - "bitsandbytes"
          - "--dtype"
          - "bfloat16"
          - "--kv-cache-dtype"
          - "auto"
          - "--gpu-memory-utilization"
          - "0.80"
          - "--max-model-len"
          - "8192"
          - "--max-num-seqs"
          - "4"
          - "--max-num-batched-tokens"
          - "1024"
        env:
          - name: PYTORCH_CUDA_ALLOC_CONF
            value: "expandable_segments:True"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: vllm-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: typhoon-vllm-service
spec:
  selector:
    app: typhoon-vllm
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi 
  storageClassName: ceph-rbd
